test: patrimoine de zety sur plusieurs périodes
hei-school/patrimoine pull request #305
Opened 2024-07-03 13:22 UTC by Mahefaa

2024-07-03 14:17 UTC, hei-teacher requested changes

2024-07-03 14:17 UTC, hei-teacher commented on src/main/java/school/hei/patrimoine/modele/possession/Possession.java
> +		if (ARIARY.equals(this.devise)) {
Non. Ce test inutile. Il faudrait convertir en Ariary les 2 valeurs. Puis c'est un détail interne du convertisseur que de s'assurer que la conversion de l'Ariary en Ariary est idempotent.

2024-07-03 14:17 UTC, hei-teacher commented on src/test/java/school/hei/patrimoine/cas/PatrimoineDeZetyTest.java
> +		System.out.println(argentEnEspècesDeZetyEn20242025.getValeurComptable());
lombok.slf4.log.debug

2024-07-03 14:17 UTC, hei-teacher commented on src/test/java/school/hei/patrimoine/cas/PatrimoineDeZetyTest.java
> +			System.out.println(argentEnEspècesProjeté.getValeurComptable() + " à " + tFutur);
sl4j

2024-07-03 14:17 UTC, hei-teacher commented on src/test/java/school/hei/patrimoine/cas/PatrimoineDeZetyTest.java
> +		for (int i = 0; true; i++) {
while(true)

2024-07-03 14:47 UTC, Mahefaa commented on src/test/java/school/hei/patrimoine/cas/PatrimoineDeZetyTest.java
> +		for (int i = 0; true; i++) {
rewritten as a do-while loop

2024-07-03 14:52 UTC, Mahefaa commented
TODO: parler de Devise.NON_NOMMEE

2024-07-08 13:29 UTC, hei-teacher approved these changes

2024-07-08 13:33 UTC, merged